name: CI Workflow
run-name: ${{ github.actor }} is running CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker Image
        run: docker build -t hello_world -f docs/dev/Dockerfile .

  lint:
    runs-on: ubuntu-latest
    needs: build
    container:
      image: hello_world
    steps:
      - uses: actions/checkout@v4
      - name: Run Lint
        run: ci/lint.sh

  test:
    runs-on: ubuntu-latest
    needs: lint
    container:
      image: hello_world
    steps:
      - uses: actions/checkout@v4
      - name: Run Tests
        run: ci/run-test.sh
